### ISSUE TITLE
Feature Request - Add IP2Location.io API as Data Source

### ISSUE THREAD

**Issue by ip2location** [redirect2me/resolvers#20]
IP2Location has launched new [IP2Location.io](https://www.ip2location.io) IP geolocation API since 2022. It is one of the fastest API in the market using servers in multiple data centers.

It has free tier which allows 30,000 queries per month. It will be good if resolvers can support the results from this API.

Feel free to ping me if you need to help. Thank you.

**Comment by fileformat** [comment]
Done!  This was actually completed awhile ago, but I forgot to close the issue.
